---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

# - name: "ZSH | Detect oh-my-zsh"
#   ansible.builtin.stat:
#     path: "{{ ansible_user_dir }}/.oh-my-zsh"
#   register: ohmyzsh
#
# - name: "ZSH | Register oh-my-zsh state"
#   ansible.builtin.set_fact:
#     ohmyzsh_is_installed: "{{ ohmyzsh.stat.exists }}"
#
# - name: "ZSH | Debug ohmyzsh_is_installed"
#   ansible.builtin.debug:
#     var: ohmyzsh_is_installed
#
# - name: "ZSH | Install oh-my-zsh"
#   when: not ohmyzsh_is_installed
#   block:
#     - name: "ZSH | Download oh-my-zsh Install Script"
#       ansible.builtin.get_url:
#         url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
#         dest: /{{ ansible_user_dir }}/oh-my-zsh.install.sh
#         force: true
#         mode: "0755"
#       notify:
#         - "ZSH | Cleanup oh-my-zsh install script"
#
#     - name: "ZSH | Run the install script"
#       ansible.builtin.script:
#         cmd: /{{ ansible_user_dir }}/oh-my-zsh.install.sh --unattended
#
# - name: "ZSH | Install Custom Plugins"
#   ansible.builtin.git:
#     repo: "{{ item.repo }}"
#     dest: "~/.oh-my-zsh/custom/plugins/{{ item.name }}"
#     update: true
#     depth: 1
#   loop:
#     - repo: https://github.com/zsh-users/zsh-autosuggestions
#       name: zsh-autosuggestions
#     # - repo: https://github.com/joshskidmore/zsh-fzf-history-search
#     #   name: zsh-fzf-history-search

- name: "ZSH | Copy .zshrc"
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"
#
- name: "ZSH | Copy .p10k.zsh"
  ansible.builtin.copy:
    src: ".p10k.zsh"
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    mode: "0644"

- name: "ZSH | Copy custom zsh config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "zsh"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "ZSH | {{ ansible_distribution }} | Identify distribution config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_distribution }}"
  register: zsh_os_distribution_config

- name: "ZSH | {{ ansible_os_family }} | Identify os family config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_os_family }}"
  register: zsh_os_family_config
  when: not zsh_os_distribution_config.stat.exists

- name: "ZSH | Calculate os config src"
  ansible.builtin.set_fact:
    zsh_os_config: "{{ zsh_os_distribution_config if zsh_os_distribution_config.stat.exists else zsh_os_family_config }}"

- name: "ZSH | Copy custom zsh config for os: {{ zsh_os_config.stat.path | basename }}"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/zsh/"
    src: "{{ zsh_os_config.stat.path }}/"
    mode: "0644"
    force: true
  when:
    - zsh_os_config is defined
    - zsh_os_config.stat.exists
